### PR TITLE
Remove enrich script

### PR DESCRIPTION
**Pull request by rajivnathan**
The enrich-by-envs-from-yaml.sh script was used to inject environment parameters into deployment yaml files since the sandbox operators used environment variables for configuration. But now that the sandbox operators have been migrated over to use ToolchainConfig for configuration this script is no longer needed.

### CODE REVIEW

**Comment by rajivnathan** [comment]
I just discovered a problem with this PR. It should not be merged yet. I'll have to come back to it to investigate so will close and re-open it.

**Comment by MatousJobanek** [comment]
> I just discovered a problem with this PR. 

What was the problem?

**Review by MatousJobanek — APPROVED** [review]
:+1: 
you can also remove the ENV from https://github.com/codeready-toolchain/toolchain-cicd/blob/master/release-operator-action/action.yml#L40

**Comment by rajivnathan** [comment]
>What was the problem?
I was hitting an error when running the `make dev-deploy-e2e` target:
https://gist.github.com/rajivnathan/1ebc79d28ec8f6a3a04ef3a7ef22cef6


But I wasn't seeing it when running `make dev-deploy-e2e-local`. It didn't really make sense to me because I thought it should be using only remote repos from master branches so I expected it to work but after tracing through the scripts I ~think~ that the problem happens in the `generate-cd-release-manifests.sh` script.

```
make -C /tmp/codeready-toolchain/host-operator publish-current-bundle ENV=dev INDEX_IMAGE_TAG=02231025 BUNDLE_TAG=02231025 QUAY_NAMESPACE=rsenthil OTHER_REPO_PATH=/tmp/codeready-toolchain/registration-service OTHER_REPO_IMAGE_LOC=quay.io/codeready-toolchain/registration-service:d6be582 IMAGE=quay.io/codeready-toolchain/host-operator:6202824
/Library/Developer/CommandLineTools/usr/bin/make run-cicd-script SCRIPT_PATH=scripts/cd/generate-cd-release-manifests.sh SCRIPT_PARAMS="-pr ../host-operator/ -er https://github.com/codeready-toolchain/registration-service -qn rsenthil -td /tmp -fr true -ch alpha -il quay.io/codeready-toolchain/host-operator:6202824 -e dev -orp /tmp/codeready-toolchain/registration-service"
running the script from GH api repo (using latest version in master)...
```

The `run-cicd-script` target prints that it's using the latest version in master but I believe `generate-cd-release-manifests.sh` is using the local cicd script because I have my GOPATH variable set and so the if condition is satisfied here:
```
if [[ -f ${GOPATH}/src/github.com/codeready-toolchain/toolchain-cicd/${OLM_SETUP_FILE} ]]; then
        source ${GOPATH}/src/github.com/codeready-toolchain/toolchain-cicd/${OLM_SETUP_FILE}
    else
        source /dev/stdin <<< "$(curl -sSL https://raw.githubusercontent.com/${OWNER_AND_BRANCH_LOCATION}/${OLM_SETUP_FILE})"
    fi
```

It took a while to figure this out but I guess that it's expected if you're modifying cicd scripts? I guess we could remove the `if [[ -f ${GOPATH}/src/github.com/codeready-toolchain/toolchain-cicd/${OLM_SETUP_FILE} ]]` block to make it behave more predictably?

**Comment by MatousJobanek** [comment]
My guess is that you executed the command with the modified host & member operators right? 
In the log that you pasted in the gist, it's visible that it fails with:
```
-e is not a recognized flag!
```
which means that when you executed the `make dev-deploy-e2e` it used the host & member repo from master which tried to pass the `-e` parameter. When you executed `make dev-deploy-e2e-local` then it was fine because the param wasn't set.

And yes, if the script is present at the gopath location, then it executes the local script. It was the easiest way to test/develop the scripts locally. 
I would vote for keeping such a functionality, but I'm open to any proposals for improvement.

**Pull request merged**
